spring.application.name=jobtracker
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true